### ISSUE TITLE
Fatal error upon activation

### ISSUE THREAD

**Issue by boxcar-studio-development** [its-cloudflare/umich-cloudflare#2]
While attempting to activate on https://ciglr.seas.umich.edu/ (running WP 6.3.5) we receive the following error:

Parse error: syntax error, unexpected ')' in /data/ciler/public_html/wp-content/plugins/umich-cloudflare-main/umich-cloudflare.php on line 683

Screenshot also attached.
![Screenshot 2024-07-24 at 10 40 09 AM](https://github.com/user-attachments/assets/95d3f18e-9161-4ee6-9ae5-70abb5c0dafa)

**Comment by nobleclem** [comment]
I was not able to replicate this issue.  I suspect your environment is stricter than mine.  Based on the code location I suspect it was due to an extra comma in the function call. Version 1.0.5 should fix this.  If not let me know.
