### ISSUE TITLE
Undefined variable $url

### ISSUE THREAD

**Issue by ferrissmith** [its-cloudflare/umich-cloudflare#3]
We're seeing regular instances of this error:
`[07-Aug-2024 19:19:11 UTC] PHP Warning: Undefined variable $url in /code/wp-content/plugins/umich-cloudflare-main/umich-cloudflare.php on line 317
[07-Aug-2024 19:19:11 UTC] PHP Warning: Undefined variable $url in /code/wp-content/plugins/umich-cloudflare-main/umich-cloudflare.php on line 319`
It doesn't look like $url is defined in the right place unless we're misreading.

**Comment by nobleclem** [comment]
Thank you.  This is now fixed in version 1.0.5.
