### ISSUE TITLE
unable to check for updates - Missing dependency error 

### ISSUE THREAD

**Issue by margglee** [its-cloudflare/umich-cloudflare#4]
Getting this issue locally and on pantheon
U-M: Cloudflare plugin is currently unable to check for updates due to a missing dependency. Please [reinstall the plugin](https://github.com/its-cloudflare/umich-cloudflare).

**Comment by nobleclem** [comment]
I am not seeing this issue on my end.  However can you check for the file vendor/umdigital/wordpress-github-updater/github-updater.php in the plugin directory on the environment where you are seeing this issue?

It should look like this: https://github.com/umdigital/wordpress-github-updater/blob/main/github-updater.php

**Comment by margglee** [comment]
I don't have the file. I just downloaded this plugin and started using it.

**Comment by nobleclem** [comment]
Based on this information I suspect that you may have downloaded the source code and not the build package file.  The build package file will be labeled as "umich-cloudflare-#.#.#.zip" in the releases assets list.

Let me know if that solves your issue.

**Comment by margglee** [comment]
Thanks. That solved it
