### ISSUE TITLE
Fatal error when marking pages as "Disable cache"

### ISSUE THREAD

**Issue by ferrissmith** [its-cloudflare/umich-cloudflare#5]
Using ver 1.0.5 we're seeing fatal errors on Page content type items when marking them as "Disable cache."
This is occurring on multiple production sites, using basic WP editor as well as Divi editor for content. The error and a Warning we're also seeing are below.

`[12-Sep-2024 14:39:24 UTC] PHP Warning:  Undefined variable $headers in /code/wp-content/plugins/umich-cloudflare/umich-cloudflare.php on line 282`

`[12-Sep-2024 14:39:24 UTC] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /code/wp-content/plugins/umich-cloudflare/umich-cloudflare.php:282
Stack trace:
#0 /code/wp-content/plugins/umich-cloudflare/umich-cloudflare.php(282): array_merge(NULL, Array)
#1 /code/wp-content/plugins/umich-cloudflare/umich-cloudflare.php(148): UMCloudflare::getRequestTTL()
#2 /code/wp-includes/class-wp-hook.php(326): UMCloudflare::{closure}(Array)
#3 /code/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#4 /code/wp-includes/class-wp.php(558): apply_filters('wp_headers', Array, Object(WP))
#5 /code/wp-includes/class-wp.php(821): WP->send_headers()
#6 /code/wp-includes/functions.php(1336): WP->main('')
#7 /code/wp-blog-header.php(16): wp()
#8 /code/index.php(17): require('/code/wp-blog-h...')
#9 {main}
  thrown in /code/wp-content/plugins/umich-cloudflare/umich-cloudflare.php on line 282`

**Comment by nobleclem** [comment]
I pushed out a fix for this.  Its in version 1.0.6.
